#ifndef __FAILSAFE_H__
#define __FAILSAFE_H__

#if defined(CONFIG_HTTPD_DEBUG)
extern int httpd_debug; /* 决定是否打印调试信息的标志 */
#endif

enum {
    WEBFAILSAFE_UPGRADE_TYPE_UNKNOWN = -1,
    WEBFAILSAFE_UPGRADE_TYPE_FIRMWARE,
    WEBFAILSAFE_UPGRADE_TYPE_UBOOT,
    WEBFAILSAFE_UPGRADE_TYPE_ART,
    WEBFAILSAFE_UPGRADE_TYPE_CDT,
    WEBFAILSAFE_UPGRADE_TYPE_GPT,
    WEBFAILSAFE_UPGRADE_TYPE_MIBIB,
    WEBFAILSAFE_UPGRADE_TYPE_SIMG,
    WEBFAILSAFE_UPGRADE_TYPE_INITRAMFS,
};

enum {
    RET_FAILURE = -1,
    RET_SUCCESS = 0,
    RET_FILE_TOO_BIG,
    RET_PART_NOT_FOUND,
    RET_WRONG_FLASH_TYPE,
    RET_WRONG_FW_TYPE,
    RET_WRONG_UPGRADE_TYPE,
};

#endif /* __FAILSAFE_H__ */
