# SPDX-License-Identifier: GPL-2.0

obj-y += backup.o
obj-y += env.o
obj-y += mibib.o
obj-y += network.o
obj-y += sysinfo.o
obj-y += syslog.o
obj-y += webterm.o
obj-$(CONFIG_FAILSAFE_MAC_MANAGEMENT) += mac.o
