#!/usr/bin/perl
use IO::Compress::Gzip qw(gzip);

open(OUTPUT, "> httpd-fsdata.c");

chdir("fsdata");

# 检查工具可用性
$html_minifier_available = 0;
$css_cleaner_available = 0;
$terser_available = 0;

if (`which html-minifier-terser 2>/dev/null`) {
    $html_minifier_available = 1;
    print "html-minifier-terser found, will minify HTML files\n";
}

if (`which cleancss 2>/dev/null`) {
    $css_cleaner_available = 1;
    print "clean-css found, will minify CSS files\n";
}

if (`which terser 2>/dev/null`) {
    $terser_available = 1;
    print "terser found, will minify JavaScript files\n";
}

# 内容类型映射表
%content_types = (
    'html' => 'text/html',
    'htm'  => 'text/html',
    'css'  => 'text/css',
    'js'   => 'text/javascript',
    'json' => 'application/json',
    'txt'  => 'text/plain',
    'xml'  => 'application/xml',
    'png'  => 'image/png',
    'jpg'  => 'image/jpeg',
    'jpeg' => 'image/jpeg',
    'gif'  => 'image/gif',
    'ico'  => 'image/x-icon',
    'svg'  => 'image/svg+xml',
    'woff' => 'font/woff',
    'woff2'=> 'font/woff2',
    'ttf'  => 'font/ttf',
    'eot'  => 'application/vnd.ms-fontobject',
);

opendir(DIR, ".");
@files =  grep { !/^\./ && !/(CVS|~)/ } readdir(DIR);
closedir(DIR);

foreach $file (@files) {
    if (-d $file && $file !~ /^\./) {
        print "Processing directory $file\n";
        opendir(DIR, $file);
        @newfiles =  grep { !/^\./ && !/(CVS|~)/ } readdir(DIR);
        closedir(DIR);
        printf "Adding files @newfiles\n";
        @files = (@files, map { $_ = "$file/$_" } @newfiles);
        next;
    }
}

foreach $file (@files) {
    if (-f $file) {
        print "Adding file $file\n";

        open(FILE, $file) || die "Could not open file $file\n";
        binmode FILE;
        read(FILE, $orig_data, -s $file);
        close(FILE);

        $path = $file;
        $path =~ s-^-/-; # 在文件路径的开头添加一个斜杠 /（用于HTTP路由）
        $fvar = $path;
        $fvar =~ s-/-_-g; # 将所有的 / 替换为 _
        $fvar =~ s-\.-_-g; # 将所有的 . 替换为 _

        # 获取文件扩展名并确定content_type
        $content_type = "application/octet-stream";  # 默认类型
        if ($file =~ /\.([^\.]+)$/) {
            $ext = $1;
            if (exists $content_types{$ext}) {
                $content_type = $content_types{$ext};
            }
        }

        $orig_size = length($orig_data);
        $uncompressed_data = $orig_data;

        # 使用专用工具压缩 HTML/CSS/JavaScript 代码
        if ($file =~ /\.html?$/ && $html_minifier_available) {
            $minified_temp = `html-minifier-terser --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-css true --minify-js true $file 2>/dev/null`;
            $minified_data = $minified_temp ? $minified_temp : $orig_data;
            $minified_size = length($minified_data);
            $uncompressed_data = $minified_data;
            print "    Minified $file: $orig_size -> $minified_size bytes (html-minifier-terser)\n";
        } elsif ($file =~ /\.css$/ && $css_cleaner_available) {
            $minified_temp = `cleancss $file 2>/dev/null`;
            $minified_data = $minified_temp ? $minified_temp : $orig_data;
            $minified_size = length($minified_data);
            $uncompressed_data = $minified_data;
            print "    Minified $file: $orig_size -> $minified_size bytes (clean-css)\n";
        } elsif ($file =~ /\.js$/ && $terser_available) {
            $minified_temp = `terser $file --compress --mangle 2>/dev/null`;
            $minified_data = $minified_temp ? $minified_temp : $orig_data;
            $minified_size = length($minified_data);
            $uncompressed_data = $minified_data;
            print "    Minified $file: $orig_size -> $minified_size bytes (terser)\n";
        }

        # 输出文件内容数组
        print(OUTPUT "char data".$fvar."[] = {\n");

        $uncompressed_size = length($uncompressed_data);
        $final_size = $uncompressed_size;

        # 对文本文件进行gzip压缩
        if ($file =~ /\.(html|css|js|txt|xml|json)$/) {
            my $gzipped_data;
            gzip \$uncompressed_data => \$gzipped_data;
            $gzip_size = length($gzipped_data);
            $final_size = $gzip_size;
            $is_gzip = 1;

            print(OUTPUT "\t/* $file (gzipped) */\n");
            print "    Compressed $file: $uncompressed_size -> $gzip_size bytes (gzip)\n";

            $i = 0;
            for ($j = 0; $j < $gzip_size; $j++) {
                if ($i == 0) {
                    print(OUTPUT "\t");
                }
                printf(OUTPUT "%#02x, ", unpack("C", substr($gzipped_data, $j, 1)));
                $i++;
                if ($i == 10) {
                    print(OUTPUT "\n");
                    $i = 0;
                }
            }
        } else {
            # 对于非文本文件（图片等），不压缩
            print(OUTPUT "\t/* $file */\n");

            $is_gzip = 0;

            $i = 0;
            for ($j = 0; $j < $uncompressed_size; $j++) {
                if ($i == 0) {
                    print(OUTPUT "\t");
                }
                printf(OUTPUT "%#02x, ", unpack("C", substr($uncompressed_data, $j, 1)));
                $i++;
                if ($i == 10) {
                    print(OUTPUT "\n");
                    $i = 0;
                }
            }
        }

        print(OUTPUT "0};\n\n");

        # 存储文件信息
        push(@fvars, $fvar);
        push(@pfiles, $file);
        push(@ppaths, $path);
        push(@porig_size, $orig_size);
        push(@puncompressed_size, $uncompressed_size);
        push(@pfinal_size, $final_size);
        push(@pis_gzip, $is_gzip);
        push(@pcontent_type, $content_type);
    }
}

print(OUTPUT "struct fs_desc httpd_filesystem[] = { \n");

for ($i = 0; $i < @fvars; $i++) {
    $file = $pfiles[$i];
    $path = $ppaths[$i];
    $fvar = $fvars[$i];
    $uncompressed_size = $puncompressed_size[$i];
    $is_gzip = $pis_gzip[$i];
    $content_type = $pcontent_type[$i];

    print(OUTPUT "\t/* $file */\n");
    print(OUTPUT "\t{\n");
    print(OUTPUT "\t\t.path = \"$path\",\n");
    print(OUTPUT "\t\t.data = data".$fvar.",\n");
    print(OUTPUT "\t\t.size = sizeof(data".$fvar.") - 1,\n");
    print(OUTPUT "\t\t.uncompressed_size = $uncompressed_size,\n");
    print(OUTPUT "\t\t.is_gzip = $is_gzip,\n");
    print(OUTPUT "\t\t.content_type = \"$content_type\",\n");
    print(OUTPUT "\t},\n\n");
}
print(OUTPUT "};\n\n");

print(OUTPUT "#define HTTPD_FS_ROOT file$fvars[$i - 1]\n");
print(OUTPUT "#define HTTPD_FS_NUMFILES $i\n");

close(OUTPUT);

# 输出统计信息
print "\n=== Compression Statistics ===\n";
$total_orig = 0;
$total_final = 0;

for ($i = 0; $i < @fvars; $i++) {
    $total_orig += $porig_size[$i];
}

for ($i = 0; $i < @fvars; $i++) {
    $total_final += $pfinal_size[$i];
}

$total_reduced = $total_orig - $total_final;

print "Total original size: $total_orig bytes\n";
print "Total final size: $total_final bytes\n";
print "Total reduced size: $total_reduced bytes\n";
